plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.desarrollox'
version = '0.0.1-SNAPSHOT'
description = 'Proyecto de construccion de apps empresariales'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	//Dependencia para leer variables de entorno(dotenv)
	implementation 'io.github.cdimascio:java-dotenv:5.2.2'

	//Dependencia para documentación de swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.12'

	// Dependencia de driver de MariaDB
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'

	// Dependencia de starter data jpa
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// Dependencia de validation hibernate
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// Dependencia de starter web
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Dependencias de Lombok
	compileOnly 'org.projectlombok:lombok:1.18.24'
	annotationProcessor 'org.projectlombok:lombok:1.18.24'

	// Dependencia de devtools
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// Dependencias de MapStruct
	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

	// Para integrar MapStruct con Lombok y no choquen
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	// Dependencia de starter security
	implementation 'org.springframework.boot:spring-boot-starter-security'

}

tasks.named('test') {
	useJUnitPlatform()
}