server.port=8080


# ===========================================
# CONFIGURACIÓN DE BASE DE DATOS
# ===========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ===========================================
# JPA / HIBERNATE
# ===========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Excluir campos null en las respuestas JSON
spring.jackson.default-property-inclusion=non_null